version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: dealhub_postgres
    environment:
      POSTGRES_DB: dealhub
      POSTGRES_USER: dealhub_user
      POSTGRES_PASSWORD: dealhub_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
